version: 2.1

refs:
  - &only_master
    filters:
      branches:
        only: master

  - &not_master
    filters:
      branches:
        ignore: master

workflows:
  test:
    jobs:
      - unit-tests:
          <<: *not_master

  release:
    jobs:
      - publish:
          <<: *only_master
          context: common-env

jobs:
  unit-tests:
    docker:
      - image: circleci/node:12
    steps:
      - setup
      - test

  publish:
    docker:
      - image: circleci/node:12
    steps:
      - setup
      - test
      - publish

commands:
  setup:
    description: 'Checkout and install dependencies'
    steps:
      - checkout
      - run:
          name: Versions
          command: node -v && npm -v && yarn -v
      - run:
          name: Install Dependencies
          command: yarn install --pure-lockfile

  test:
    steps:
      - run:
          name: Test
          command: yarn test

  publish:
    steps:
      - run:
          name: NPM Auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Release
          command: npx rollingversions publish
